name: Upgrade software
description: Select a software package
title: "[Upgrade]: "
labels: ["upgrade"]
assignees:
  - AnonymousWP
body:
  - type: dropdown
    id: Software package
    attributes:
      label: Select the software you want to update
      multiple: false
      options:
        - Graylog
        - OpenSearch
        - MongoDB
        - Docker Compose
        - Graylog Terraform Provider
    validations:
      required: true
