name: Update software
description: Select a software package
title: "[Update]: "
labels: ["update"]
assignees:
  - AnonymousWP
body:
  - type: dropdown
    id: Software-package
    attributes:
      label: Select the software you want to update
      multiple: false
      options:
        - Graylog
        - OpenSearch
        - MongoDB
        - Docker Compose
        - Graylog Terraform Provider
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Enter the new version of the software package and a link to the changelog
      value: |
      Version: 
      Link to changelog: 
    validations:
      required: true
